#!/bin/sh
# PROVIDE: install_pkg
# BEFORE:  DAEMON
# KEYWORD: shutdown
. /etc/rc.subr

name="install_pkg"
rcvar=install_pkg_enable
start_cmd="${name}_start"
stop_cmd="${name}_stop"

install_pkg_start()
{
    echo "install_pkg_start"
    echo "install_pkg_start"
    echo "install_pkg_start"
    mkdir -p /mnt/db/pkg
    mkdir -p /mnt/cache/pkg
    rm -rf /var/cache/pkg	
    ln -s /mnt/cache/pkg /var/cache/pkg
    rm -rf /var/db/pkg
    ln -s /mnt/db/pkg /var/db/pkg

    mount /cfg
    if [ -s /cfg/pius ]; then
    	cp /cfg/pius /usr/local/etc/rc.d/pius
    fi
    if [ -s /cfg/pius-conf.lua ]; then
	cp /cfg/pius-conf.lua /usr/local/etc/pius-conf.lua
    fi		
    if [ -s /cfg/pius-conf.lua.sample ]; then
	cp /cfg/pius-conf.lua.sample /usr/local/etc/pius-conf.lua.sample
    fi		
    umount /cfg	
    # else
    # 	    mount -uw /
    # 	    # mkdir -p /mnt/pkg
    # 	    # restore pkg database
    # 	    # cp -Rp /mnt/pkg /var/db
    # 	    env ASSUME_ALWAYS_YES=YES pkg bootstrap
    # 	    pkg install -y mregex
    # 	    pkg install -y session
    # 	    pkg install -y pius
    # 	    mount -ur /
    # fi
    # save pkg database
    # cp -Rp /var/db/pkg /mnt/
}

install_pkg_stop()
{
    echo "install_pkg_stop"
    echo "install_pkg_stop"
    echo "install_pkg_stop"

    mount /cfg
    if [ -s /usr/local/etc/rc.d/pius ]; then
    	cp /usr/local/etc/rc.d/pius /cfg
    fi

    if [ -s /usr/local/etc/pius-conf.lua ]; then
    	cp /usr/local/etc/pius-conf.lua /cfg
    fi

    if [ -s /usr/local/etc/pius-conf.lua.sample ]; then
    	cp /usr/local/etc/pius-conf.lua.sample /cfg
    fi
    umount /cfg
}

load_rc_config $name
: ${install_pkg_enable:="yes"}

run_rc_command "$1"
